
import { Button, VerticalBox } from "std-widgets.slint";


export component AppWindow inherits Window {
    title: "小工具";
    width: 480px;
    height: 340px;
    in-out property <string> error_message: "";
    in-out property <string> success_message: "";
    in-out property <string> wu_status: "未知";
    in-out property <string> wu_action_text: "";
    in-out property <string> xbox_status: "未知";
    callback enable-xbox-recording();
    callback disable-xbox-recording();
    callback toggle-windows-update();
    callback add-xiaohe-doublepinyin();
    callback remove-xiaohe-doublepinyin();
    callback pause-windows-update();
    Rectangle {
        background: #fafbfc;
        border-radius: 12px;
        width: parent.width;
        height: parent.height;
        VerticalLayout {
            spacing: 18px;
            y: 24px;
            Rectangle {
                background: #fff;
                border-radius: 8px;
                width: parent.width - 48px;
                height: 70px;
                x: 24px;
                VerticalLayout {
                    spacing: 6px;
                    Text {
                        text: "Windows 更新";
                        font-size: 15px;
                        font-weight: 500;
                        horizontal-alignment: left;
                        color: #222;
                    }

                    HorizontalLayout {
                        spacing: 16px;
                        Text {
                            text: "状态：" + root.wu_status;
                            // font-size: 13px;
                        }

                        Button {
                            text: root.wu_action_text;
                            // font-size: 13px;
                            min-width: 70px;
                            min-height: 28px;
                            clicked => {
                                root.toggle-windows-update();
                            }
                        }

                        Button {
                            text: "暂停30天更新";
                            // font-size: 13px;
                            min-width: 90px;
                            min-height: 28px;
                            clicked => {
                                root.pause-windows-update();
                            }
                        }
                    }
                }
            }

            Rectangle {
                background: #fff;
                border-radius: 8px;
                width: parent.width - 48px;
                height: 70px;
                x: 24px;
                VerticalLayout {
                    spacing: 6px;
                    Text {
                        text: "输入法小鹤双拼";
                        font-size: 15px;
                        font-weight: 500;
                        horizontal-alignment: left;
                        color: #222;
                    }

                    HorizontalLayout {
                        spacing: 16px;
                        Button {
                            text: "添加小鹤双拼";
                            // font-size: 13px;
                            min-width: 90px;
                            min-height: 28px;
                            clicked => {
                                root.add-xiaohe-doublepinyin();
                            }
                        }

                        Button {
                            text: "删除小鹤双拼";
                            // font-size: 13px;
                            min-width: 90px;
                            min-height: 28px;
                            clicked => {
                                root.remove-xiaohe-doublepinyin();
                            }
                        }
                    }
                }
            }

            Rectangle {
                background: #fff;
                border-radius: 8px;
                width: parent.width - 48px;
                height: 70px;
                x: 24px;
                VerticalLayout {
                    spacing: 6px;
                    Text {
                        text: "Xbox 屏幕录制";
                        font-size: 15px;
                        font-weight: 500;
                        horizontal-alignment: left;
                        color: #222;
                    }

                    HorizontalLayout {
                        spacing: 16px;
                        Text {
                            text: "状态：" + root.xbox_status;
                            // font-size: 13px;
                        }

                        Button {
                            text: "开启";
                            // font-size: 13px;
                            min-width: 60px;
                            min-height: 28px;
                            clicked => {
                                root.enable-xbox-recording();
                            }
                        }

                        Button {
                            text: "禁用";
                            // font-size: 13px;
                            min-width: 60px;
                            min-height: 28px;
                            clicked => {
                                root.disable-xbox-recording();
                            }
                        }
                    }
                }
            }
        }
    }
}
