import { Button } from "std-widgets.slint";
export component InfoDialog inherits Rectangle {
    in property <string> message;
    callback on_close();
    background: #80000000;
    border-radius: 0px;
    width: 100%;
    height: 100%;
    Rectangle {
        background: white;
        border-radius: 8px;
        width: 300px;
        height: 160px;
        x: (parent.width - self.width) / 2;
        y: (parent.height - self.height) / 2;
        Text {
            text: root.message;
            color: #080;
            font-size: 16px;
            x: 16px;
            y: 32px;
            width: parent.width - 32px;
        }

        Button {
            text: "关闭";
            x: parent.width / 2 - self.width / 2;
            y: parent.height - self.height - 16px;
            clicked => {
                root.on_close();
            }
        }
    }
}
