# 每次push tag标签的时候触发
on:
  push:
    tags:
      - "*"
name: Build and Publish program
# 构建win程序并发布
jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: x86_64-pc-windows-msvc

      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-

      - name: Build release version
        run: cargo build --release --target x86_64-pc-windows-msvc

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            target/x86_64-pc-windows-msvc/release/*.exe
          generate_release_notes: true
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
